##
# (c) 2021-2026
#     Cloud Ops Works LLC - https://cloudops.works/
#     Find us on:
#       GitHub: https://github.com/cloudopsworks
#       WebSite: https://cloudops.works
#     Distributed Under Apache v2.0 License
#
name: 'auto-readme'

on:
  # Open a PR to update README (as necessary)
  pull_request: 
    types: 
      - opened
      - synchronize
      - reopened

  # Update README nightly
  schedule:
    - cron:  '0 0 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: readme/update
        shell: bash
        env:
          GITHUB_TOKEN: "${{ secrets.BOT_TOKEN }}"
        run: |
          make init
          make readme/deps
          make readme
      # Create a PR only if not on a pull request event (to avoid error)
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        if: (github.event_name != 'pull_request')
        with:
          labels: automated pr
          token: ${{ secrets.BOT_TOKEN }}
          commit-message: Update README.md
          title: Automatic Update of README.md
          body: |-
            This is an auto-generated PR which updates the `README.md` from the `README.yaml` 
            using the [`cloudopsworks/tronador`](https://github.com/cloudopsworks/tronador).
          branch: feature/auto-readme
          #branch-suffix: none
      # Push the code into PR if we are in a pull request event
      - name: Push changes
        if: (github.event_name == 'pull_request')
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git add README.md docs/
          git commit -m "Updated README.md" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }} || echo "No changes to push"